trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'macos-latest'  # Usa 'macos-latest' si planeas compilar para iOS y Android.

variables:
  flutterSdkVersion: 'stable'

stages:
  - stage: Setup
    displayName: "Setup Flutter"
    jobs:
      - job: InstallFlutter
        displayName: "Install Flutter SDK"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              git clone https://github.com/flutter/flutter.git -b $(flutterSdkVersion)
              echo '##vso[task.prependpath]$(pwd)/flutter/bin'
              flutter --version
            displayName: "Install Flutter SDK"

  - stage: Analyze
    displayName: "Analyze Code"
    dependsOn: Setup
    jobs:
      - job: AnalyzeCode
        displayName: "Flutter Analyze"
        steps:
          - script: flutter pub get
            displayName: "Get Dependencies"

          - script: flutter analyze
            displayName: "Run Flutter Analyze"

  - stage: Test
    displayName: "Run Tests"
    dependsOn: Analyze
    jobs:
      - job: RunTests
        displayName: "Run Flutter Tests"
        steps:
          - script: flutter test
            displayName: "Run Unit Tests"

  - stage: Build
    displayName: "Build Application"
    dependsOn: Test
    jobs:
      - job: BuildApp
        displayName: "Build Flutter App"
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                flutter pub get
                flutter build apk --release
                flutter build ios --release
            displayName: "Build APK and IPA"

  - stage: Deploy
    displayName: "Deploy to Stores"
    dependsOn: Build
    jobs:
      - job: DeployAndroid
        displayName: "Deploy Android APK (omitido Google Play)"
        steps:
          - script: |
              echo "Skipping Google Play deployment."
            displayName: "Skip Google Play Deployment"

      - job: DeployiOS
        displayName: "Deploy iOS IPA (omitido App Store)"
        steps:
          - script: |
              echo "Skipping App Store deployment."
            displayName: "Skip App Store Deployment"
